# Generated by Django 4.1.4 on 2023-01-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
